name: AWS

on:
  push:
    branches:
      - main   # or your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sankeerthbd
          password: sanki@1234

      - name: Build Docker image
        run: |
          docker build -t sankeerthbd/aws:latest .

      - name: Tag Docker image
        run: |
          docker tag sankeerthbd/aws:latest sankeerthbd/aws:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push sankeerthbd/aws:latest


      - name: Deploy Docker container via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: 54.147.38.177
          SERVER_USER: ubuntu
        run: |
          ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" $SERVER_USER@$SERVER_IP << 'EOF'
            docker pull sankeerthbd/aws:latest
            bash /home/$SERVER_USER/AWS/scripts/stop_container.sh
            bash /home/$SERVER_USER/AWS/scripts/start_container.sh
          EOF
