name: Deploy Flask App

on:
  push:
    branches:
      - main    # or your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t sankeerthbd/aws:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker tag sankeerthbd/aws:latest ${{ secrets.DOCKER_USERNAME }}/aws:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/aws:latest

      - name: Deploy Docker container via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" $SERVER_USER@$SERVER_IP << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/aws:latest
            bash /home/$SERVER_USER/AWS/scripts/stop_container.sh
            bash /home/$SERVER_USER/AWS/scripts/start_container.sh
          EOF
